# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title: "Bella Steinbeck"
description: "Data Analyst | Data Scientist"
url: "https://bellasteinbeck.github.io"
baseurl: ""
